name: Foxy Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  foxy_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:foxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: foxy
          coverage-result: false
          skip-tests: true
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }